[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'pyyaml', 'pybind11']

[project]
name = 'rpi-libcamera'
version = '0.1a6'
description = 'libcamera python bindings'
readme = 'README.md'

[project.urls]
Source = "https://github.com/raspberrypi/pylibcamera"
"RPi libcamera Source" = "https://github.com/raspberrypi/libcamera"

[tool.meson-python.args]
setup = [
    '-Drevision=v0.3.1+rpt20240906',
    '-Drepository=https://github.com/raspberrypi/libcamera.git',
    '-Dversion=v0.3.1+50-69a894c4'
]

[tool.flit.module]
name = "libcamera"
